dist: xenial
language: python
python:
  - "3.7"
before_install:
  - sudo apt-get install -y tesseract-ocr
install:
  - pip install aiohttp aiofiles codecov nose pytesseract
script: nosetests --with-coverage
after_success:
  - codecov
