dist: xenial
language: python
python:
  - "3.7"
before_install:
  - sudo apt-get install -y tesseract-ocr
install:
  - pip install -r requirements.txt
  - pip install codecov
script: nosetests --with-coverage --cover-package=cli --cover-package=httpapi \
--cover-package=httpclient --cover-package=image --cover-package=ocrapi
after_success:
  - codecov
